name: Build Windows EXE

on:
  workflow_dispatch:        # 手动触发；也可改为 push/tag 触发

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'          # 任选 ≥3.9 ≤3.12 的官方 Windows 轮子都有

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller test2.spec
        dir dist

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ImageAnnotator
        path: dist/ImageAnnotator.exe
