name: Build Windows EXE

on:
  workflow_dispatch        # 手动触发；可改成 push / tag

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # ───── 安装依赖（PowerShell，使用 ` 续行） ─────
    - name: Install dependencies
      run: |
        python -m pip install -U pip
        pip install `
          shapely==2.0.3 `
          rasterio==1.3.9 `
          fiona==1.9.6 `
          pyproj==3.6.1 `
          opencv-python==4.11.0.0 `
          PyQt5==5.15.9 `
          PyQt5-Qt5==5.15.2 `
          PyQt5-sip==12.13.0 `
          openpyxl `
          numpy
        pip install pyinstaller

    - name: Build EXE with PyInstaller
      run: pyinstaller test2.spec

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ImageAnnotator
        path: dist/ImageAnnotator.exe
