name: build-exe
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install binary wheels
      run: |
        python -m pip install -U pip
        pip install shapely==2.0.3 rasterio==1.3.9 fiona==1.9.6 ^
                    pyproj==3.6.1 opencv-python==4.11.0.0 ^
                    PyQt5==5.15.9 PyQt5-Qt5==5.15.2 PyQt5-sip==12.13.0 ^
                    openpyxl numpy

        pip install pyinstaller

    - name: Build exe
      run: pyinstaller test2.spec

    - uses: actions/upload-artifact@v4
      with:
        name: ImageAnnotator
        path: dist/ImageAnnotator.exe
